version: v1.0

plan: standard-2

global_job_config:
  setup:
    - checkout
    - neetoci-version ruby 3.1.3
    - bundle config path 'vendor/bundle'
    - cache restore
    - bundle install --jobs 1
    - cache store
  jobs:
    - name: CiChecks
      commands:
        - bundle exec rake validate

triggers:
  - event: branch
    branch_name: main
  - event: pull_request
